### PR TITLE
light mode

### PR DESCRIPTION
**Pull request by nicholascok**
added support for light mode theme. also fixed a minor bug where signalling SIGINT did not restore the user's terminal state.

### CODE REVIEW

**Comment by SmokeyTheKat** [comment]
Remove the "Light Mode" feature because its bad and blinding and my eyes hurt. The signal code is good. Will merge after that. :)

**Comment by nicholascok** [comment]
no mfer it's light mode or no mode 😎😎😎

**Comment by nicholascok** [comment]
2023-07-28-221510_1920x1200_scrot

**Comment by nicholascok** [comment]
for the record, it was beautiful.

**Pull request closed without merging**
